name: CI/CD Pipeline for Kubernetes

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push Docker images
      - name: Build and Push Docker Images
        run: |
          docker build -t pillivinay/frontend:latest ./frontend
          docker build -t pillivinay/backend:latest ./backend
          docker push pillivinay/frontend:latest
          docker push pillivinay/backend:latest

      # Step 5: Set up Google Cloud credentials
      - name: Set up GKE credentials
        run: |
          echo "${{ secrets.GKE_SERVICE_ACCOUNT_KEY }}" | base64 --decode > $HOME/gcloud-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
          gcloud config set project ${{ secrets.PROJECT_ID }}
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.PROJECT_ID }}

      # Step 6: Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
